### ISSUE TITLE
Missing type definitions for `Capacity` and `Geometry`

### ISSUE THREAD

**Issue by julianrojas87** [smart-data-models/dataModel.OSLO#4]
In the [context.jsonld](https://github.com/smart-data-models/dataModel.OSLO/blob/master/context.jsonld) there are no definitions for the types: [`Capacity`](https://github.com/smart-data-models/dataModel.OSLO/blob/a95c5126e8fb0fe201bf20cf407cf47cb8eda3bd/BicycleParkingStation/examples/example-normalized.jsonld#L7) and [`Geometry`](https://github.com/smart-data-models/dataModel.OSLO/blob/a95c5126e8fb0fe201bf20cf407cf47cb8eda3bd/BicycleParkingStation/examples/example-normalized.jsonld#L17)

**Comment by albertoabellagarcia** [comment]
You mean these ones?: 
 "ParkingFacility.capacity": "https://smartdatamodels.org/dataModel.OSLO/ParkingFacility.capacity",
"InfrastructureElement.geometry": "https://smartdatamodels.org/dataModel.OSLO/InfrastructureElement.geometry",
or other different ones?

**Comment by julianrojas87** [comment]
[ParkingFacility.capacity](https://smartdatamodels.org/dataModel.OSLO/ParkingFacility.capacity) and [InfrastructureElement.geometry](https://smartdatamodels.org/dataModel.OSLO/InfrastructureElement.geometry) are properties. I mean definitions for the Types "Capacity" and "Geometry" instead. In the same way as we have a Type definition for [BicycleParkingStation](https://smartdatamodels.org/dataModel.OSLO/BicycleParkingStation).

**Comment by albertoabellagarcia** [comment]
Where are these types defined in the OSLO ontology?

**Comment by julianrojas87** [comment]
You can find the definitions for [Capacity](https://github.com/smart-data-models/dataModel.OSLO/blob/master/notes_context.jsonld#L108) and [Geometry](https://github.com/smart-data-models/dataModel.OSLO/blob/33cec8ac29bfab01bad878aeefc1927bb8130036/notes_context.jsonld#L176) in the JSON-LD context that comes from the [OSLO ontology](https://purl.eu/doc/applicationprofile/mobility/passenger-transport-hubs/erkendestandaard/2022-12-01/context/OSLO-PassengerTransportHubs-AP_en.jsonld).

See also the ontology documentation for [Capacity](https://purl.eu/doc/applicationprofile/mobility/passenger-transport-hubs#Capacity) and [Geometry](https://purl.eu/doc/applicationprofile/mobility/passenger-transport-hubs#Geometry).

**Comment by albertoabellagarcia** [comment]
But as long as this exact types Capacity and geometry are not used but these [ParkingFacility.capacity](https://smartdatamodels.org/dataModel.OSLO/ParkingFacility.capacity) and [InfrastructureElement.geometry](https://smartdatamodels.org/dataModel.OSLO/InfrastructureElement.geometry) I have no way to include them.

**Comment by albertoabellagarcia** [comment]
If you have further questions please reopen this issue
